tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'getantibody/tap'

brew 'antibody'
brew 'git'
brew 'go'
brew 'gnupg'
brew 'tig'
brew 'tmux'
brew 'fzf'
brew 'rsync'
brew 'zsh'
brew 'ansible'
brew 'openssh'
brew 'exa'

cask 'iterm2'
cask 'google-chrome'
cask 'docker'
cask 'atom'
cask 'visual-studio-code'
cask 'jetbrains-toolbox'
cask 'tunnelblick'
cask 'microsoft-office'
cask 'font-hack'
cask 'sourcetree'
