# _exports
export EDITOR='nvim'
export DOTFILES="$HOME/.dotfiles"

# _load zsh plugins
source ~/.zsh_plugins.sh

# _source aliases
#source ~/.dotfiles/zsh/aliases/alias.zsh
#source ~/.dotfiles/zsh/functions/functions.zsh
source ~/.dotfiles/zsh/functions/fzf.zsh
#source ~/.dotfiles/zsh/aliases/git.zsh
#source ~/.dotfiles/zsh/aliases/vim.zsh
#source ~/.dotfiles/zsh/aliases/cd.zsh
#source ~/.dotfiles/zsh/aliases/dev.zsh
#source ~/.dotfiles/zsh/aliases/app.zsh
#source ~/.dotfiles/zsh/zsh/bindings.zsh

setopt autocd

# _secret configs
[[ -e ~/.secrets ]] && source ~/.secrets

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' matcher-list +'l:|=* r:|=*'

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

setopt NO_BG_NICE # don't nice background tasks
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS # allow functions to have local traps
setopt HIST_VERIFY
setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
setopt IGNORE_EOF

setopt APPEND_HISTORY # adds history
setopt INC_APPEND_HISTORY SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS
